version: '3.1'
services:
  app:
    container_name: springnative
    image: springnative
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - pg
  pg:
    image: postgres
    ports:
      - "5440:5440"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cars
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5440/cars